#!/bin/sh
if echo "$1" | grep -E '^[0-9]+x[0-9]+$' > /dev/null; then
	resolution="$1"
	shift
else
	resolution=800x600
fi

Xephyr -br -ac -noreset -screen "$resolution" :1 &
until DISPLAY=:1 "$@"; do sleep 0.1 ; done
